### ISSUE TITLE
[Invokes] commands should be dash delimited 

### ISSUE THREAD

**Issue by jakearchibald** [openui/open-ui#1072] opened 2024-07-17 10:51 UTC
https://w3ctag.github.io/design-principles/#casing-rules

So `toggle-muted` rather than `toggleMuted`.

Custom commands would need to be identified some other way, eg start with `-`.

**Comment by keithamus** [comment] 2024-07-20 17:16
Duplicate of https://github.com/openui/open-ui/issues/969

**Closed by keithamus** 2024-07-20 17:16 UTC
