### ISSUE TITLE
[popup]Two nested popups dismissed by only one outside click 

### ISSUE THREAD

**Issue by ziyunfei** [openui/open-ui#575] opened 2022-08-06 06:43 UTC
I don't know if this is a spec bug or implementation bug?

![1](https://user-images.githubusercontent.com/1276859/183237755-7c29a896-2bbb-4958-b03b-ffc2eb7701d3.gif)

```
<button popuptoggletarget="popup1">按钮1</button>

<div id="popup1" class="popup" popup>
  弹窗1
  <button popuptoggletarget="popup2">按钮2</button>
</div>

<div id="popup2" class="popup" popup>
  弹窗2
</div>

<style>
.popup {
    width: 100px;
    height: 100px;
    display: grid;
    place-content: center;
    position: absolute;
    left: 0;
    top: 100px;
}

[popup] {
    opacity: 0;
    transition: opacity 0.2s;
}

[popup]:top-layer {
    opacity: 1;
}

[popup]::backdrop {
    background: #000a
}
</style>
```

**Comment by ziyunfei** [comment] 2022-08-06 07:12
The reason is ::backdrop has `pointer-event: none`
<img width="726" alt="image" src="https://user-images.githubusercontent.com/1276859/183238581-d734d443-b563-4351-8173-a0384c6557f0.png">

**Comment by mfreed7** [comment] 2022-08-11 17:31
Thanks for raising the issue. So this is by design, and this is working as intended. Whether you have one open pop-up or several stacked ones (as in your example), clicking outside all of them will light-dismiss them all. If, in your example, you were to offset the nested pop-up a bit, so you could still see the bottom pop-up, you would be able to click on that bottom pop-up and it would stay open. I.e. that click would be outside the nested pop-up, so it would close, but it would be within the bottom pop-up, so that would stay open.

Also note that you can hit ESC and only the topmost pop-up will close. ESC just pops the topmost one off the stack.

Let me know if this answers your question. You can read more about this behavior in [this section of the explainer](https://open-ui.org/components/popup.research.explainer#light-dismiss).

**Comment by mfreed7** [comment] 2022-08-17 20:10
I'm going to close this, but feel free to re-open it if my comment above didn't address the issue.

**Closed by mfreed7** 2022-08-17 20:10 UTC
Labels: popup
