### ISSUE TITLE
Light dismiss on page scroll?

### ISSUE THREAD

**Issue by dandclark** [openui/open-ui#240] opened 2020-12-10 18:23 UTC
Discussed this yesterday with @bocupp-microsoft, @melanierichards, @ipopescu93

The definition of "light dismiss" at https://open-ui.org/components/select#light-dismiss states that `<select>` closes when the user hits escape, or when focus moves outside of the listbox due to user action or script.

Should "light dismiss" also occur when the page is scrolled?  Our thinking is that yes, it should, because like a focus change this indicates user intent to switch their attention to other content on the page, so a popup like the `<select>` listbox should be closed.

At the same time we should consider panning (e.g. pinch zoom on a mobile device).  We think this should *not* cause light dismiss, because unlike scrolling, the user is probably still interested in the current content.  For example they may be zooming in to see it better, so it would be wrong to close it.

Note, the "light dismiss" definition currently lives inside `<select>` but I expect it to generalize to other control types that have a popup. See also #241.

Thoughts?

**Comment by gregwhitworth** [comment] 2020-12-12 18:23
@melanierichards did you do any light dismiss research to possibly inform the direction here based on common paradigms or any user studies?

**Comment by mrmckeb** [comment] 2020-12-13 18:09
I've seen this technique many times, but from experience, it's often used as a way to avoid expensive recalculations of absolutely positioned popup containers.

You can see this in effect in this example:
https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown

If that is the primary reason people are implementing selects in this way, then it might be solved by providing a more flexible select, or a reusable popup component.

**Comment by gregwhitworth** [comment] 2020-12-15 03:40
Looking at a variety of browsers they seem to dismiss on scroll, as @mrmckeb this seems to be common in component libraries as well. Browsers, do not allow scrolling however on the page if hit-testing is on the popup however (this is consistent in all UAs). 

Looking at a few other component libs: 

* Evergreen - Doesn't dismiss on scroll and allows scrolling while mouse is over the popup
* Material - Doesn't dismiss on scroll and allows scrolling while mouse is over the popup
* Lightning - Uses native select for the popup
* AntDesign - Doesn't dismiss on scroll and allows scrolling while mouse is over the popup
* Atlassian - Doesn't dismiss on scroll but doesn't scroll when mouse is over popup
* Carbon - Uses native select for the popup

I prefer the scrolling to not occur when the mouse is over the popup, especially since some selects will have a scroller and keeping them consistent I think is good. I am a bit indifferent on whether it should dismiss or not if the mouse is outside of the popup. It's a pretty evenly split between component libs and UAs here.

**Comment by una** [comment] 2020-12-16 20:06
I think this could be an unintended behavior. For example, If one is filling out a form, opens the select, and then realizes the select overflows the page, they would need to scroll down to get it into view. If the select `lightdissmiss`-es, the user won't know how far down to scroll to re-center it, and it would require another click open. This feels like an annoying behavior, and  is particularly relevant on mobile, as you mention above with zoom.

**Comment by mrmckeb** [comment] 2020-12-17 09:03
I think it would be great to reach out to some people that have implemented this behaviour to understand why they did.

My theory is that in many cases, this is a workaround for managing the complexity of fixed position elements on scroll and/or locking scroll when selects are open.

I also _prefer_ that scroll is locked when the select is open. I don't feel that dismissing/closing on scroll is the right path.

**Comment by Malvoz** [comment] 2020-12-27 15:03
FYI there may be some overlap/similarities between this suggested "light dismiss" (on scroll) and the proposed "modal close signals" (https://github.com/WICG/proposals/issues/18). I.e. the [explainer](https://github.com/slightlyoff/history_api/blob/master/history_and_modals.md) talks about "a custom picker input (e.g. date picker)" but does not mention scrolling as a signal for closing it. Maybe that's a consideration to bring up there?

**Comment by ericwbailey** [comment] 2021-01-12 01:45
I agree with @mrmckeb. I'd also caution about this kind of dismissal pattern from a motor disability perspective (hand tremors, Parkinson's, accidental jostling, etc.).

**Comment by melanierichards** [comment] 2021-01-14 17:58
Adding data for native `<select>`:

* **Chromium-based browsers (Win, Mac):** scrolling with mouse "over" `select` popup window does not dismiss the window. Scrolling elsewhere does dismiss. There seems to be a little bit of buggy behavior where I can get the popup window to stick around, but it behaves as if it is `position: fixed`, rather than scrolling along with the in-page portion of the control
* **Firefox (Win, Mac):** scrolling with mouse "over" `select` popup window does not dismiss the window. Scrolling elsewhere does dismiss.
* **IE :) (Win):** page scroll interactions are completely blocked when the popup is open.
* **Safari (Mac):** page scroll interactions are completely blocked when the popup is open.

No one persists the popup and maintains its position relative to the in-page portion of the select control.

**Comment by melanierichards** [comment] 2021-04-12 20:03
Added tags to clarify that this applies to `<selectmenu>` (customizable select) and `popup`. Not an exhaustive list for applicability.

**Comment by mfreed7** [comment] 2022-03-24 18:40
[Another bug was reported](https://github.com/openui/open-ui/issues/497) that requests that scrolling **not** trigger light dismiss. In particular, it has a [particularly good demo](https://codesandbox.io/s/selectmenu-example-n9tl49?file=/src/SelectFontFamily.tsx) showing a use case that would be broken. (Scroll the text down a bit, and then click on either of the Font or Size pulldowns, and hover a different option. There's a scroll due to changing text size, which light dismisses the selectmenu.) 

Reading back through the discussion on this issue, it sounds like the general consensus is also **not** to light dismiss on scroll, from a user's point of view. The condition to light dismiss on scroll was primarily added (IMHO) as a performance consideration related to anchor positioning. The way the anchor positioning discussion is going, however, sounds like that won't be as important.

**Comment by mfreed7** [comment] 2022-03-31 19:11
Based on the discussion generally, and the meeting/resolution just now, I'm going to close this issue. Thanks everyone!

**Closed by mfreed7** 2022-03-31 19:11 UTC
Labels: select, agenda+, popup
