### ISSUE TITLE
[Select] Keep popup open when another element scrolls

### ISSUE THREAD

**Issue by luncheon** [openui/open-ui#497] opened 2022-03-17 05:56 UTC
The current Chromium implementation of `<selectmenu>` closes the popup when scrolling occurs outside of that element.
This behavior makes it hard to implement “Live Preview” feature (like MS Office).

It looks: hover an `<option>` -> content size changes -> scroll position changes -> popup closes.

(Look at the scrollbar.)

https://user-images.githubusercontent.com/7709610/158744082-189d9140-8ce7-487d-b955-63cefcc327e9.mp4

CodeSandbox:
https://codesandbox.io/s/selectmenu-example-n9tl49?file=/src/SelectFontFamily.tsx

Smaller example on CodePen:
https://codepen.io/luncheon/pen/mdpeRvV

This may not be a behavior that needs to be specified in the specification, but please consider supporting Live Preview.
(Whether or not Live Preview is supported, I think it is inconvenient to close the popup when scrolling.)

**Comment by mfreed7** [comment] 2022-03-24 18:40
Thanks for reporting this issue. [Your demo](https://codesandbox.io/s/selectmenu-example-n9tl49?file=/src/SelectFontFamily.tsx) does make a very compelling case for *not* light dismissing on scroll.

This is a duplicate of https://github.com/openui/open-ui/issues/240, so I'm going to close it. But I'll add a comment there referencing your point of view and demo page.

**Closed by mfreed7** 2022-03-24 18:40 UTC

**Comment by luncheon** [comment] 2022-03-24 22:25
Thank you😊
