### ISSUE TITLE
Proposal for Exclusive Accordions

### ISSUE THREAD

**Issue by dbaron** [openui/open-ui#725] opened 2023-04-24 13:44 UTC
I've started writing an [explainer for Exclusive Accordions](https://open-ui.org/components/accordion.explainer).

I'm interested in feedback on this proposal, either here or in separate issues.

**Comment by bkardell** [comment] 2023-04-26 21:05
@scottaohara https://github.com/openui/open-ui/issues/700#issuecomment-1496634485 :)

**Comment by scottaohara** [comment] 2023-04-27 12:38
Ayup

**Comment by gregwhitworth** [comment] 2023-05-23 20:51
@dbaron does this need to stay open given the explainer has landed generally?

**Comment by dbaron** [comment] 2023-05-23 21:13
I was hoping to use this issue for continued general discussion about the explainer -- and I was hoping to have another round of that discussion.

In particular, while there are two separate threads of discussion (details styling, and improvements to a11y of summary), I was hoping to share a status update (have a prototype in Chromium), quickly present some demos (hoping to share those tomorrow), and discuss next steps.  (I think I've addressed the feedback from the previous round, though I want to go through a few lists of things again to check.)

**Comment by ZoeBijl** [comment] 2023-08-02 22:13
What’s the user need for these exclusive accordions?

**Comment by dbaron** [comment] 2023-08-03 01:19
I attempted to [describe the user needs](https://open-ui.org/components/accordion.explainer/#user-needs) in the explainer.

**Comment by scottaohara** [comment] 2023-08-03 12:22
i think the explainer might need to more overtly call out that the HTML PR to make exclusive accordions doesn't address [the existing issues](https://open-ui.org/components/accordion.explainer/#existing-issues-with-details) that are mentioned in the explainer.

That should probably be repeated in the user needs section, since bullets one (i think) and two (absolutely) are not addressed by the existing HTML pr

**Comment by ZoeBijl** [comment] 2023-08-03 15:14
> I attempted to [describe the user needs](https://open-ui.org/components/accordion.explainer/#user-needs) in the explainer.

To be honest all I see there are developer needs. 

> keyboard shortcuts and focus handling,

With the complexities around keyboard support for tabs I kinda doubt people will pick up keyboard support for accordions any better.

> exposure via ARIA to assistive technology, and

Can you explain how this would result in better communication of relevant information than either an `<article>` with a bunch of `<sections>`/`<details><summary>` inside?

> integration with browser features such as find-in-page.

I don’t know enough about this to comment anything other than “that sounds good”.

On a separate note, the explainer mentions open questions for panelset:

> The panelset proposal has enough open questions that it’s a bit hard to assess.

Given the similarities between the issues that panelset and this proposal are trying to solve—can you explain how this proposal answers/solves those questions?

Further questions:

* Why would the parsing of the `open`-attribute be any different from `checked` in radiobuttons?
* Has there been any user research into the usefulness of this pattern?

I’m not against adding `name` as an attribute for `<details>` though I wonder what the added benefit is to say wrapping them in a named `<article>` or `<section>`.

---

As an aside / personal opinion: exclusive accordions should die in a hellish fire; they deserve nothing more after all the frustration they’ve caused me and countless others—please let me see content when and how I want it…

**Comment by mikemai2awesome** [comment] 2023-08-11 16:07
Regarding this section:

> Accordions with exactly one item open
>
> Some accordions (such as the one on the Pixel product page above) always have exactly one item open, and do not allow zero items to be open. (This could be called an exact-exclusive accordion.) This is a somewhat more complicated widget, because the open/close control disappears from the item that is open or becomes disabled. It’s not clear how such widgets could be modeled with this design, other than by ensuring that developer Javascript to handle this.

This is the only true accordion example from the research. Everything else is just grouped disclosures (each item can expand or collapse), meaning multiple summary/details inside a section or group already describes it precisely, nothing new needs to be created.

If we were to create something new, then it should be this thing that "has exactly one item open, and do not allow zero items to be open", and the screen reader announcement for such a thing should be using the "selected" language rather than the "expanded | collapsed" language, because you cannot collapse the current item.

> [accessible name], selected, 1 of 3

Screen reader users are already exposed to this "selected" language with Tabs and Radio Inputs, where similarly you can only select 1 at a time and you cannot collapse it.

**Comment by yatil** [comment] 2023-11-01 10:46
This seems to be shipping in Chromium and Safari TP. Without the affordances for users to overwrite this behavior, which is actively introducing an accessibility barrier to the web. Users with memory issues will have a harder time, screen reader users don’t have (optionally) access to all headings on a page. Currently, they can opt to open all details elements at once. Removing this feature for users on the author’s behalf makes the web less accessible. 

Please make sure that none of this ships until there has been a proper feature set that allows for accessibility for all users of the web. It’s extremely disappointing to see the web community actively building barriers into the platform. **The rollout of exclusive accordions must be stopped now.**

**Comment by lukewarlow** [comment] 2023-11-01 11:50
@yatil the roll out of this feature is down to the specific browser vendors so raise bugs in the appropriate venues if you consider this a show stopping issue.

**Comment by lukewarlow** [comment] 2023-11-01 11:52
I'm going to go ahead and close this issue out as the OpenUI aspect of this is done. We have an explained and implementations. If people want to discuss with OpenUI specific issues or extras with the proposal feel free to file specific issues.

**Closed** 2023-11-01 11:52 UTC

**Comment by yatil** [comment] 2023-11-01 11:57
@lukewarlow So, just so I understand what OpenUI does: It lets individual vendors create explainers without any accessibility oversight or discussion or even specifying user needs in the user needs sections and when those vendors go ahead and implement those untested, non-discussed features, then it’s just the way it is? Good to know, I guess.

**Comment by lukewarlow** [comment] 2023-11-01 12:00
No that's not at all what OpenUI does but we don't have control over when vendors decide to ship functionality. So commenting here to stop the rollout isn't effective.

As said above please raise an issue to discuss your specific concerns if there's something you think OpenUI can help you with, we can discuss accessibility affordances.

It's worth noting that this isn't just implemented by the specific vendor that proposed it either.

**Comment by MattWilcox** [comment] 2023-11-01 12:12
Can I suggest that you _make accessibility_ your problem? This is unacceptable. If there is a clear problem in the blueprint being provided for others to implement, it is not then the implementors problem when they implement your blueprints.

This is a bad blueprint with not enough thought behind it. It is harmful. Please consider how this happened and how to avoid this again. This proposal does no one any favours. No one.

**Comment by yatil** [comment] 2023-11-01 12:16
Considering that OP is a vendor employee, and I’m just a mere freelance person with no power at all, this seemed to be the correct avenue to comment. And yes, I expect from anyone contributing to the web to do their accessibility homework.

**Comment by lukewarlow** [comment] 2023-11-01 13:27
To clarify I simply meant the proposal this issue is for has been accepted into openUI and an explained landed and implemented so *this* (aka bringing a proposal forward) is done.

As for follow up work I think open UI can play a role but as you say WHATWG etc might be better.

**Comment by cookiecrook** [comment] 2023-11-15 22:34
@MattWilcox wrote:
> Can I suggest that you _make accessibility_ your problem? This is unacceptable. […] This proposal does no one any favours. No one.

and @yatil wrote:
> And yes, I expect from anyone contributing to the web to do their accessibility homework. 

Before responding on the technical merits of various arguments, and hopefully without seeming dismissive of commenters concerns, I'd like to request the conversation remain as objective and respectful as possible. 

We're all very passionate about the Web Platform (I personally about its accessibility), but I'm reading emotion into a few responses, that even when warranted, doesn't usually lead to a productive solution. There have been multiple, documented, cases of specific members of W3C accessibility groups (thankfully neither of you) who have bullied other W3C contributors into quitting their jobs or exceedingly negative outcomes far beyond what I hope was their intention. (Truly unacceptable behavior, IMO.) People get especially passionate about accessibility, since it is often interlinked with a personal connection to disability, so tempers flare more than in other groups. We all need to be actively conscious to keep the discussion civil and respectful, without challenging each other's competencies or motivations. Thanks for considering.

I couldn't easily find an OpenUI-specific Code of Conduct, so I'll reference the W3C document instead:
https://www.w3.org/Consortium/cepc/#expected-behavior

Responses/Question to the technical concerns coming in a follow-up comment.

**Comment by cookiecrook** [comment] 2023-11-15 23:09
Regarding some of the technical arguments @yatil raised:

> Without the affordances for users to overwrite this behavior, which is actively introducing an accessibility barrier to the web. Users with memory issues will have a harder time, screen reader users don’t have (optionally) access to all headings on a page. 

In response to the last point about SR heading navigation, I recall there is another existing issue for search (including accessibility search) within hidden contents of collapsed summary elements. So that issue (I'm hopeful someone can help me local the tracking issue) may be resolved in future updates using the native summary element. Note that the same problem cannot be solved with the myriad of custom accordions and disclosures that have been shipping for decades using headings hidden with `display:none`.

In response to the main issue, the primary value of OpenUI (and ARIA for that matter) as I see it is an acknowledgement that web developers have jumped through hoops for decades to create controls that are complex, and many times inaccessible. Even when the controls are possible to be made accessible (as with an ARIA retrofit), many web developers don't do it correctly. The OpenUI project (literally started with accessibility as one of its primary goals) seeks to make it easier for web developers to build these control in a way that the browser engines can make them accessible. 

Similarly, custom dialogs (mostly inaccessible) shipped for decades before the HTML Dialog API was available... Now it's easier for developers to use, and most accessibility bugs can be addressed by the rendering engine rather than putting the onus on the web developer to jump through hoops. (Aside: Truly accessible focus management of dialogs was exceedingly difficult; even the ARIA Authoring Practices doesn't get it right. It was just too difficult before `inert` shipped, requiring the `capture` phase of `focus` and `blur` event handling.)

The accordion pattern is in a similar state. Web developers have been using them for decades. Many times without any thought to accessibility... The ARIA Practices acknowledges this as a valid control type, and published an [Authoring Practices guide for Accordions](https://www.w3.org/WAI/ARIA/apg/patterns/accordion/) which from a usability perspective, is functionally equivalent to Tabs.

@yatil wrote:
> Users with memory issues will have a harder time [using an accordion pattern]

I acknowledge that may be true, and guidance should be given wrt when they should not be used. For example, this [User Experience Stack Exchange thread](https://ux.stackexchange.com/questions/23181/when-is-it-bad-practice-to-use-an-accordion-control) lists many mainstream considerations.

But ultimately it's going to be up to the web developer to decide what common UI pattern they choose, and this OpenUI feature takes an existing pattern and makes it more accessible than before for assistive technology users. As specific problems arise and are discovered, they can be made more accessible in the engine, rather than requiring the web developer or framework developer to update.

@yatil @MattWilcox If you still feel this pattern is an anti-pattern, do you also recommend ARIA APG remove the progressive disclosure patterns like Accordions and Tabs? If not, why not? Or what's the benefit you see in those that isn't even more beneficial in this OpenUI pattern for the same UI?

**Comment by yatil** [comment] 2023-11-15 23:30
(I will not comment on the tone comment.)

> If you still feel this pattern is an anti-pattern, do you also recommend ARIA APG remove the progressive disclosure patterns like Accordions and Tabs? If not, why not? Or what's the benefit you see in those that isn't even more beneficial in this OpenUI pattern for the same UI?

I think patterns that are beneficial should be put in HTML. The issue is not with having or not having exclusive accordions. 

The question is about having exclusive accordions that are now much easier to implement because they are a native part of the web, but without any fixes for people with accessibility needs. 

Browsers must provide those overrides to allow affected users to bypass them, if it gets into the native web platform.

It makes a huge difference if a pattern is native to the web. We still have terrible inaccessible date and time picker when it was done last time.

And yes, I think if tabs go native, browsers should give users options to see all tabs linearized, for example.

That this stuff is hard, of course it is. We have the responsibility of doing the hard things. And the hard things mean having a proper wide accessibility review. Sure, it is convenient to have a new HTML feature hammered out in 9 months, but this ”move fast, break things” mentality is not the correct way for the web. We cannot afford to break things, because things stay broken (see date/time inputs).

Yes, exclusive accordions are a bad pattern when implemented using JavaScript and when implemented using native features. But when we implement them natively, we should also agree to empower users to soften the worst impacts of this. That there is apparently no consensus on this and “we provide developer information” is the best the group could come up with is sad.

**Comment by cookiecrook** [comment] 2023-11-15 23:53
Okay. Glad to know we agree on several of the sticking points, and that the details are being worked out in other open issues like #925 and https://github.com/w3c/html-aam/issues/509.
